### ISSUE TITLE
motr build errors

### ISSUE THREAD

**Issue by rupasree-roy** [Seagate/cortx-motr#1248]
Am trying to run FDMI sample applications using `sudo fdmi/plugins/fdmi_plugins_st.sh`

However, while trying to build motr (for running the plugins) am getting some errors. Am following this Quickstart guide to build motr - https://github.com/Seagate/cortx-motr/blob/47e7b4aa1d87588cde7aed517e35dc0eb2e2c870/doc/Quick-Start-Guide.rst

Step 1 ran without any issues : 
![image](https://user-images.githubusercontent.com/66809998/142933807-d5cbfea4-8d95-47b8-b0e8-741a258e1b56.png)

This is the LNET NIDs: 
```
[root@cortx-fdmi cortx-motr]# sudo lctl list_nids
10.0.0.201@tcp
```

And when I check if the libfaric package is installed it gives me this : 
```
[root@cortx-fdmi cortx-motr]# fi_info --version
fi_info: 1.11.2
libfabric: 1.11.2
libfabric api: 1.11
```
I tried couple of ways to remove libfab :
![image](https://user-images.githubusercontent.com/66809998/142935442-30c0ca8e-95da-43cb-911b-fff02306c29b.png)

![image](https://user-images.githubusercontent.com/66809998/142935487-3026a3e3-a4ea-498c-8c30-0c7d1fca6d99.png)

It says libfab package not installed but when I check fi_info version it does show me libfab. I also removed /etc/libfab.conf file. How do I get rid of libfab?  

And while trying to rebuild motr using 'scripts/m0 rebuild' am getting the following error : 
![image](https://user-images.githubusercontent.com/66809998/142936843-1a47f156-4c1a-4ae9-96cd-1274bc7f462a.png)

I can share complete log if required. 
I also tried running the command `sudo ./scripts/m0 run-st 60*` and I am getting the following error while running that - 
![image](https://user-images.githubusercontent.com/66809998/142937360-3d400968-bc1a-4986-8641-04959ec3b3e3.png)

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/EOS-26563. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by yanqingfu** [comment]
try to use this method to remove libfab package: https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/711230113/Libfabric+setup+and+using+libfabric+with+motr#Uninstalling-libfabric-package

**Comment by nkommuri** [comment]
Suggest to update lnet section of QSG to point to this doc, for uninstallation of libfab

**Comment by nkommuri** [comment]
QSG is updated in the PR https://github.com/Seagate/cortx-motr/pull/1256

@rupasree-roy  Please let us know your issue is resolved or not? Thanks.

**Comment by rupasree-roy** [comment]
@yanqingfu Thanks, I was able to remove libfabric using the link that you had shared. 

```
fi_info --verison
-bash: /usr/local/bin/fi_info: No such file or directory
```
@nkommuri 
However while I try to run the fdmi_plugin_st.sh its still giving me errors: 
![image](https://user-images.githubusercontent.com/66809998/143317267-107b13f0-8eac-409f-a0df-9b4a534028c0.png)

**Comment by zohebkhann** [comment]
@rupasree-roy After removing libfabric code,  use "scripts/m0 rebuild" command to re-build Motr. Then run fdmi_plugin_st.sh.
 It should work without any issues.
![image](https://user-images.githubusercontent.com/89624145/143573143-76bbccce-a41e-4ece-9ec7-53fa9a2eb1de.png)

**Comment by rupasree-roy** [comment]
@zohebkhann I did `scripts/m0 rebuild` and then ran the fdmi_plugin_st.sh but still getting errors: 

![image](https://user-images.githubusercontent.com/66809998/143667897-d2a0910b-d567-4380-b09a-d608add320a0.png)

**Comment by zohebkhann** [comment]
@rupasree-roy Could you please let us know the hash used?

**Comment by rupasree-roy** [comment]
@zohebkhann not sure where to get the hash from.

**Comment by zohebkhann** [comment]
@rupasree-roy Go to` cortx-motr ` directory(cloned repo dir) and do git log. The topmost(latest) commit hash is the hash we are looking for.

**Comment by rupasree-roy** [comment]
Okay you meant commit hash. Its 5021c35a33f7cf6535a030434a22382b0756cb9c. 
![image](https://user-images.githubusercontent.com/66809998/144111728-f26b1349-3dd9-40bd-b61a-40612aad80f2.png)

**Comment by zohebkhann** [comment]
@rupasree-roy Could please try with latest code changes. Commit hash that you are using is old.
![image](https://user-images.githubusercontent.com/89624145/144181203-6eda59ae-5ea6-4da2-b49f-2b84c193a14b.png)

**Comment by rupasree-roy** [comment]
@zohebkhann I tried with the latest code: 
![image](https://user-images.githubusercontent.com/66809998/144381159-789ad6af-449d-4a82-8f79-775a0746e20d.png)
### 
[fdmi_test_result.txt](https://github.com/Seagate/cortx-motr/files/7640115/fdmi_test_result.txt)
I am attaching the log after running the fdmi_plugin_st.sh. I don't see any kv's being created as per the script and its giving some error messages as well.

**Comment by rupasree-roy** [comment]
@zohebkhann @JugalPatil helped to resolve this issue. 
motr build was failing due to firewall and fdmi plugin was failing due to low space. 

Disabled firewalld and added two more disks to the VM ( each 10G ). 
Cleared /tmp folder, /var/crash

**Comment by nkommuri** [comment]
Closing as the issue is resolved.

**Comment by cortx-admin** [comment]
> Nagakishore Kommuri commented in Jira Server:

Issue resolved. Github issue closed.

**Comment by cortx-admin** [comment]
> Nagakishore Kommuri commented in Jira Server:

.

**Comment by cortx-admin** [comment]
> Nagakishore Kommuri commented in Jira Server:

.

**Comment by johnbent** [comment]
@rupasree-roy , did you learn how to diagnose this yourself for the future? If so, it would be a great contribution to document this somewhere. If you create a new page to do so, please make sure to add a link to it from an existing page.

**Comment by johnbent** [comment]
Exactly! Let me know if you want to meet to discuss this.

**Comment by rupasree-roy** [comment]
Sure John. Will look into your calendar and schedule a meeting.

Thanks,
Rupasree
________________________________
